services:
  app-container:
    build: .
    ports:
      # - [host]:[container]
      - '${PORT}:3000'
    links:
      - mongo-container
    env_file:
      - .env.local
  mongo-container:
    image: mongo
    ports:
      - '${MONGODB_PORT}:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
